/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as VideoRouteImport } from './routes/video'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBeritaRouteImport } from './routes/admin.berita'
import { Route as AdminGaleriRouteImport } from './routes/admin.galeri'
import { Route as AdminHeaderRouteImport } from './routes/admin.header'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'
import { Route as AdminVideoRouteImport } from './routes/admin.video'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriRoute = AdminGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeaderRoute = AdminHeaderRouteImport.update({
  id: '/header',
  path: '/header',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideoRoute = AdminVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AdminRoute,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeritaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/video': typeof VideoRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/video': typeof AdminVideoRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/video': typeof VideoRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/video': typeof AdminVideoRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/berita': typeof BeritaRouteWithChildren
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/profil': typeof ProfilRoute
  '/video': typeof VideoRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/header': typeof AdminHeaderRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/video': typeof AdminVideoRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/video'
    | '/admin/berita'
    | '/admin/galeri'
    | '/admin/header'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/video'
    | '/berita/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/video'
    | '/admin/berita'
    | '/admin/galeri'
    | '/admin/header'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/video'
    | '/berita/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/berita'
    | '/galeri'
    | '/kontak'
    | '/profil'
    | '/video'
    | '/admin/berita'
    | '/admin/galeri'
    | '/admin/header'
    | '/admin/login'
    | '/admin/pengaturan'
    | '/admin/video'
    | '/berita/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeritaRoute: typeof BeritaRouteWithChildren
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  ProfilRoute: typeof ProfilRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeri': {
      id: '/admin/galeri'
      path: '/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AdminGaleriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/header': {
      id: '/admin/header'
      path: '/header'
      fullPath: '/admin/header'
      preLoaderRoute: typeof AdminHeaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/video': {
      id: '/admin/video'
      path: '/video'
      fullPath: '/admin/video'
      preLoaderRoute: typeof AdminVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof BeritaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminGaleriRoute: typeof AdminGaleriRoute
  AdminHeaderRoute: typeof AdminHeaderRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminVideoRoute: typeof AdminVideoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBeritaRoute: AdminBeritaRoute,
  AdminGaleriRoute: AdminGaleriRoute,
  AdminHeaderRoute: AdminHeaderRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminVideoRoute: AdminVideoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BeritaRouteChildren {
  BeritaSlugRoute: typeof BeritaSlugRoute
}

const BeritaRouteChildren: BeritaRouteChildren = {
  BeritaSlugRoute: BeritaSlugRoute,
}

const BeritaRouteWithChildren =
  BeritaRoute._addFileChildren(BeritaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeritaRoute: BeritaRouteWithChildren,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  ProfilRoute: ProfilRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
